name: shoq
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.1.2
  firebase_database: ^12.1.3
  firebase_storage: ^13.0.6
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  encrypt: ^5.0.3
  crypto: ^3.0.3
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.0.0
  url_launcher: ^6.2.5
  device_info_plus: ^12.3.0
  intl: ^0.20.2
  provider: ^6.1.1         
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  file_picker: ^10.3.10
  cached_network_image: ^3.3.1 
  mime: ^2.0.0
  path_provider: ^2.1.4
  open_filex: ^4.4.0
  path: ^1.9.0
  sodium: ^3.4.6
  flutter_secure_storage: ^10.0.0
  sodium_libs: ^3.4.6

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#0A0A23"
  adaptive_icon_foreground: "assets/images/logo.png"


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
