name: shoq
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.5.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  encrypt: ^5.0.3
  crypto: ^3.0.3
  firebase_messaging: ^15.2.10 
  url_launcher: ^6.2.5
  device_info_plus: ^10.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#0A0A23"
  adaptive_icon_foreground: "assets/images/logo.png"


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/